function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function toNum(p){return Number(String(p||0).replace(/[^0-9.]/g,''))||0}
function fmt(p){var n=Number(String(p||0).replace(/[^0-9.]/g,''));return A$'+(n||0).toFixed(2)}

function changeQty(i,d){var items=getCart();items[i].qty=(items[i].qty||1)+d;if(items[i].qty<1)items[i].qty=1;saveCart(items);renderCart();updateNavCart()}
function removeItem(i){var items=getCart(),removed=items[i];items.splice(i,1);saveCart(items);renderCart();updateNavCart();toast('Removed: '+esc(removed.title||'item'))}
function saveForLater(i){var items=getCart(),it=items[i];try{var wl=JSON.parse(localStorage.getItem('bd_wishlists_v2')||'null');if(wl&&wl.items){wl.items.push({id:'wl_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),product:it,folderId:'__default__',added:new Date().toISOString(),variants:it.variants||'',alertsOn:!1});localStorage.setItem('bd_wishlists_v2',JSON.stringify(wl))}}catch(e){}
items.splice(i,1);saveCart(items);renderCart();updateNavCart();toast('❤️ Saved for later: '+esc(it.title||'Item'))}
function updateSummary(){var items=getCart(),sub=items.reduce(function(s,i){return s+toNum(i.price)*(i.qty||1)},0);document.getElementById('summary-subtotal').textContent=fmt(sub);var disc=promoDiscount||0,total=Math.max(0,sub-disc);if(disc>0){document.getElementById('promo-line').style.display='flex';document.getElementById('summary-discount').textContent='-'+fmt(disc)}else document.getElementById('promo-line').style.display='none';document.getElementById('summary-total').textContent=fmt(total)}
function togglePromo(){document.getElementById('promo-field').classList.toggle('show')}
function applyPromo(){var code=(document.getElementById('promo-input').value||'').trim().toUpperCase();if(!code){toast('Enter a promo code');return}var items=getCart(),sub=items.reduce(function(s,i){return s+toNum(i.price)*(i.qty||1)},0);if(code==='SAVE10'){promoDiscount=Math.round(sub*0.1*100)/100;promoCode='SAVE10'}else if(code==='FREESHIP'){promoDiscount=0;promoCode='FREESHIP'}else{toast('Invalid promo code');return}document.getElementById('promo-field').classList.remove('show');document.getElementById('promo-applied').classList.add('show');document.getElementById('promo-code-name').textContent=promoCode;document.getElementById('promo-saved').textContent=promoDiscount>0?'-'+fmt(promoDiscount):'Free Shipping';document.getElementById('promo-input').value='';updateSummary();toast('Promo applied!')}
function removePromo(){promoCode='';promoDiscount=0;document.getElementById('promo-applied').classList.remove('show');updateSummary();toast('Promo removed')}
function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tid);t._tid=setTimeout(function(){t.classList.remove('show')},2000)}
function updateNavCart(){try{var items=getCart(),n=items.reduce(function(s,i){return s+(i.qty||1)},0),b=document.getElementById('nav-cart-count');if(b){b.textContent=n;b.style.display=n>0?'':'none'}}catch(e){}}
renderCart();updateNavCart();