function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function toNum(p){return Number(String(p||0).replace(/[^0-9.]/g,''))||0}
function fmt(p){return @\n' + toNum(p).toFixed(2)}
var pC='',pD=0;
function getCart(){try{return JSON.parse(localStorage.getItem('bd_cart')||'[]')}catch(e){return[]}}
function saveCart(a){localStorage.setItem('bd_cart',JSON.stringify(a))}
function renderCart(){var it=getCart(),c=document.getElementById('cart-items'),e=document.getElementById('empty-state'),s=document.getElementById('summary-section'),b=document.getElementById('cart-count-badge'),ic=document.getElementById('cart-item-count');if(b)b.textContent=it.length?'('+it.length+')':'';var tq=it.reduce(function(s,i){return s+(i.qty||1)},0);if(ic)ic.textContent=tq+' item'+(tq!==1?'s':'');if(!it.length){c.innerHTML='';e.style.display='block';s.style.display='none';return}e.style.display='none';s.style.display='block';var h='';it.forEach(function(x,i){var p=toNum(x.price),cp=toNum(x.comparePrice||x.compare_at_price||0),hd=cp>p,ct=hd?Math.round((1-p/cp)*100):0,img=x.image||(x.images||[])[0]||'';h+='<div class="cart_item"><a href="product.html?id='+esc(x.id||'')+'" class="cart_img">'+(img?'<img src="'+esc(img)+'" onerror="this.remove()" alt="">':'')+(hd?'<span class="cart_discount_badge">-'+ct+'%</span>':'')+'</a><a href="product.html?id='+esc(x.id||'')+'" class="cart_info"><div class="cart_title">'+esc(x.title||'Untitled')+'</div>'+(x.variants?'<div class="cart_variant">'+esc(x.variants)+'</div>':'')+'<div class="cart_pricing">'+(hd?'<span class="cart_original">'+fmt(cp)+'</span>':'')+'<span class="cart_price">'+fmt(p)+'</span></div><div class="qty_row"><button class="qty_btn" onclick="changeQty('+i+',-1)" '+((x.qty||1)<=1?'disabled':'')+'>−</button><span class="qty_val">'+(x.qty||1)+'</span><button class="qty_btn" onclick="changeQty('+i+',1)">+</button><span class="qty_remove" onclick="removeItem('+i+')">📕 Remove</span><span class="qty_save" onclick="saveForLater('+i+')">❤️ Save</span></div></a></div>'});c.innerHTML=h;updateSummary()}
function changeQty(i,d){var it=getCart();it[i].qty=(it[i].qty||1)+d;if(it[i].qty<1)it[i].qty=1;saveCart(it);renderCart();updateNavCart()}
function removeItem(i){var it=getCart();it.splice(i,1);saveCart(it);renderCart();updateNavCart();toast('Removed')}
function saveForLater(i){var it=getCart(),x=it[i];try{var wl=JSON.parse(localStorage.getItem('bd_wishlists_v2')||'null');if(wl&&wl.items){wl.items.push({id:'wl_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),product:x,folderId:'__default__',added:new Date().toISOString(),variants:x.variants||'',alertsOn:!1});localStorage.setItem('bd_wishlists_v2',JSON.stringify(wl)}}}catch(e){}it.splice(i,1);saveCart(it);renderCart();updateNavCart();toast('Saved')}
function updateSummary(){var it=getCart(),sub=it.reduce(function(s,i){return s+toNum(i.price)*(i.qty||1)},0);document.getElementById('summary-subtotal').textContent=fmt(sub);var disc=pD||0,tot=Math.max(0,sub-disc);if(disc>0){document.getElementById('promo-line').style.display='flex';document.getElementById('summary-discount').textContent='-'+fmt(disc)}else document.getElementById('promo-line').style.display='none';document.getElementById('summary-total').textContent=fmt(tot)}
function togglePromo(){document.getElementById('promo-field').classList.toggle('show')}
function applyPromo(){var code=(document.getElementById('promo-input').value||'').trim().toUpperCase();if(!code){toast('Enter code');return}var it=getCart(),sub=it.reduce(function(s,i){return s+toNum(i.price)*(i.qty||1)},0);if(code==='SAVE10){pD=Math.round(sub*0.1*100)/100;pC='SAVE10'}else if(code==='FREESHIP'){pD=0;pC='FREESHIP'}else{toast('Invalid');return}document.getElementById('promo-field').classList.remove('show');document.getElementById('promo-applied').classList.add('show');document.getElementById('promo-code-name').textContent=pC;document.getElementById('promo-saved').textContent=pD>0?'-'+fmt(pD):'Free';document.getElementById('promo-input').value='';updateSummary();toast('Applied')}
function removePromo(){pc='';pD=0;document.getElementById('promo-applied').classList.remove('show');updateSummary();toast('Removed')}
function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tid);t._tid=setTimeout(function(){t.classList.remove('show')},2000)}
function updateNavCart(){try{var it=getCart(),n=it.reduce(function(s,i){return s+(i.qty||1)},0),b=document.getElementById('nav-cart-count');if(b){b.textContent=n;b.style.display=n>0?'':'none'}}catch(e){}}
renderCart();updateNavCart();