/* Wishlist V2 - State + Render + Cart All-in-One */
var BDWL=function(){try{var r=JSON.parse(localStorage.getItem('bd_wishlists_v2'));if(r&&r.folders&&r.items)return r}catch(){}var old;try{old=JSON.parse(localStorage.getItem('bd_wishlist')||'[]')}catch(){}old=old||[];return{folders:[{id:'__all__',name:'All Items',builtin:true},{id:'__default__',name:'Favourites',builtin:false}],items:old.map(function(it){return{id:'wl_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),product:it,folderId:'__default__',added:it.added||new Date().toISOString(),variants:it.variants||'',alertsOn:false}}),alertsOn:false,privacyViewOnly:false}}();
var activeFolder='__all__';function save(){localStorage.setItem('bd_wishlists_v2',JSON.stringify(BDWL))}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function fmt(p){return 'A$'+(Number(String(p||0).replace(/[^0-9.]/g,''))||0).toFixed(2)}
function resolvePrice(it){var p=Number(String(it.product.price||0).replace(/[^0-9.]/g,''))||0,cp=Number(String(it.product.comparePrice||0).replace(/[^0-9.]/g,''))||0;return{price:p,comparePrice:cp,hasDiscount:cp>p,discountPct:cp>p?Math.round((1-p/cp)*100):0}}
function getStockLabel(it){if(it.product.stock===0)return{cls:'in_stock',label:'In Stock'};if(it.product.stock<=5&&it.product.stock>0)return{cls:'low_stock',label:'Low Stock'};if(it.product.stock===0)return{cls:'out',label:'Out of Stock'};if(it.product.backordered)return{cls:'backordered',label:'Backordered'};return{cls:'in_stock',label:'In Stock'}}
function getItems(){return activeFolder==='__all__'?BDWL.items.slice():BDWL.items.filter(function(i){return i.folderId===activeFolder})}
function switchFolder(id){activeFolder=id;renderFolders();renderCards()}
function addFolder(){var c=document.getElementById('folder-tabs');if(c.querySelector('.folder_pill_new'))return;var s=document.createElement('span');s.className='folder_pill active';s.innerHTML='<span class="folder_pill_new"><input placeholder="List name..." id="new-folder-input"><button onclick="commitFolder(event)">✓</button></span>';document.getElementById('add-folder-btn').replaceWith(s);setTimeout(function(){document.getElementById('new-folder-input');if(i)i.focus()},100)}
function commitFolder(e){e.stopPropagation();var n=(document.getElementById('new-folder-input')||{}).value;if(!(n||'').trim()){renderFolders();return}var f={id:'f_'+Date.now(),name:n.trim(),builtin:false};BDWL.folders.push(f);activeFolder=f.id;save();renderFolders();renderCards()}
function deleteFolder(id){if(!confirm('Delete this list? Items move to Favourites.'))return;BDWL.items.forEach(function(i){if(i.folderId===id)i.folderId='__default__'});BDWL.folders=BDWL.folders.filter(function(f){return f.id!==id});if(activeFolder===id)activeFolder='__all__';save();renderFolders();renderCards()}
function renderFolders(){var h='';BDWL.folders.forEach(function(f){var n=f.id==='__all___'?BDWL.items.length:BDWL.items.filter(function(i){return i.folderId===f.id}).length;h+='<span class="folder_pill'+(f.id===activeFolder?' active':'')+'" onclick="BDSET.folder(\''+f.id+'\')">'+esc(f.name);if(!f.builtin)h+='<span class="folder_pill_count">'+n+'</span>';if(!f.builtin&&f.id!=='__default__')h+='<button class="folder_pill_remove" onclick="event.stopPropagation();deleteFolder(\''+f.id+'\')">🖃</button>';h+='</span>'});h+='<span class="folder_pill folder_pill_add" id="add-folder-btn" onclick="addFolder()">+ New List</span>';document.getElementById('folder-tabs').innerHTML=h}
function renderCards(){var items=getItems(),s=document.getElementById('sort-select');if(s){var sv=s.value;items.sort(function(a,b){if(sv==='price-asc')return (Number(String(a.product.price||0).replace(/[^0-9.]/g,''))||0)-(Number(String(b.product.price||0).replace(/[^0-9.]/g,''))||0);if(sv==='price-desc')return (Number(String(b.product.price||0).replace(/[^0-9.]/g,''))||0)-(Number(String(a.product.price||0).replace(/[^0-9.]/g,''))||0);if(sv==='name')return(a.product.title||'').localeCompare(b.product.title||'');return new Date(b.added||0)-new Date(a.added||0)})}
var c=document.getElementById('cards'),e=document.getElementById('empty'),t=document.getElementById('toolbar'),f=document.getElementById('sticky-footer');if(!items.length){c.innerHTML='';e.style.display='block';t.style.display='none';f.classList.remove('open');return}
e.style.display='none';t.style.display='flex';f.classList.add('open');document.getElementById('footer-count').textContent=items.length;document.getElementById('footer-total').textContent=fmt(items.reduce(function(s,i){return s+(Number(String(i.product.price||0).replace(/[^0-9.]/g,''))||0)},0));var h='';items.forEach(function(it){var p=resolvePrice(it),st=getStockLabel(it),img=it.product.image||(it.product.images||[])[0]||'',added=it.added?new Date(it.added):null,adtext=added?added.toLocaleDateString('en-AU',{day:'umeric',month:'short'}):'';h+='<div class="card"><a href="product.html?id='+esc(it.product.id||'')+'" class="card_img">'+(img?'<img src="'+esc(img)+'" onerror="this.remove()" alt="">':'')+(p.hasDiscount?'<span class="discount_badge">-'+p.discountPct+'</span>':'')+'</a><a href="product.html?id='+esc(it.product.id||'')+'" class="card_info"><div class="card_title">'+esc(it.product.title||'Untitled')+'</div>'+(it.variants?'<div class="card_variant">'+esc(it.variants)+' · <span class="card_variant_edit" onclick="event.preventDefault();editVariants(\''+esc(it.id)+'\')">Edit</span></div>':'')+'<div class="card_pricing">'+(|
 hasDiscount?'<span class="card_original">'+fmt(p.comparePrice)+'</span>':'')+'<span class="card_price">'+fmt(p.price)+'</span></div><div class="card_meta"><span class="card_stock '+st.cls+'">'+st.label+'</span>'+(adtext?'<span class="card_added">Added '+adtext+'</span>':'')+'</div></a><div class="card_actions"><button class="card_remove" onclick="removeItem(\''+esc(it.id)+'\')" title="Remove">✕</button><button class="card_cart" onclick="addToCart(\''+esc(it.id)+'\')">Add to cart</button></div></div>'});c.innerHTML=h}