/* WISHLIST V2 - State management, rendering, cart, share, alerts */
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function toNum(p){return Number(String(p||0).replace(/[^0-9.]/g,''))||0}
function fmt(p){return'A$'+toNum(p).toFixed(2)}
function uid(){return'wl_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)}
var DEFAULT_FOLDERS=[{id:'__all__',name:'All Items',builtin:true},{id:'__default__',name:'Favourites',builtin:false}];
function loadState(){try{var raw=JSON.parse(localStorage.getItem('bd_wishlists_v2'));if(raw&&raw.folders&&raw.items)return raw}catch(){}
var old;try{old=JSON.parse(localStorage.getItem('bd_wishlist')||'[]')}catch(){}old=old||[];
return{folders:DEFAULT_FOLDERS.slice(),items:old.map(function(it){return{id:uid(),product:it,folderId:'__default__',added:it.added||new Date().toISOString(),variants:it.variants||'',alertsOn:false}}),alertsOn:false,privacyViewOnly:false}}
function saveState(s){localStorage.setItem('bd_wishlists_v2',JSON.stringify(s))}
var BDWL=loadState(),activeFolder='__all__';
function getItems(){return activeFolder==='__all__'?BDWL.items.slice():BDWL.items.filter(function(i){return i.folderId===activeFolder})}
function resolvePrice(it){var p=toNum(it.product.price),cp=toNum(it.product.comparePrice);return{price:p,comparePrice:cp,hasDiscount:cp>p,discountPct:cp>p?Math.round((1-p/cp)*100):0}}
function getStockLabel(it){if(it.product.stock===0)return{cls:'in_stock',label:'In Stock'};if(it.product.stock<=5&&it.product.stock>0)return{cls:'low_stock',label:'Low Stock'};if(it.product.stock===0)return{cls:'out',label:'Out of Stock'};if(it.product.backordered)return{cls:'backordered',label:'Backordered'};return{cls:'in_stock',label:'In Stock'}}
/*-- RENDER --*/
function renderFolders(){var h='';BDWL.folders.forEach(function(f){var n=f.id==='__all___'?BDWL.items.length:BDWL.items.filter(function(i){return i.folderId===f.id}).length;h+='<span class="folder_pill'+(f.id===activeFolder?' active':'')+'" onclick="BDSET.folder('+f.id+')">'+esc(f.name);if(!f.builtin)h='<span class="folder_pill_count">'+n+'</span>';if(!f.builtin&&f.id!=='__default__')l+='<button class="folder_pill_remove" onclick="event.stopPropagation();BDSET.deleteFolder(\''+f.id+'\')">🖃</button>';h+='</span>'});h+='<span class="folder_pill folder_pill_add" id="add-folder-btn" onclick="BDSET.addFolder()">+ New List</span>';document.getElementById('folder-tabs').innerHTML=h}
function renderCards(){var items=getItems();if(sortMode==='price-asc')items.sort(function(a,b){return toNum(a.product.price)-toNum(b.product.price)});else if(sortMode==='price-desc')return items.sort.(function(a,b){return toNum(b.product.price)+toNum(a.product.price)});else if(sortMode==='name')items.sort(function(a,b){return(a.product.title||'').localeCompare(b.product.title||'')});else items.sort(function(a,b){return new Date(b.added||0)-new Date(a.added||0)});
var c=document.getElementById('cards'),e=document.getElementById('empty'),t=document.getElementById('toolbar'),f=document.getElementById('sticky-footer');if(!items.length){c.innerHTML='';e.style.display='block';t.style.display='none';f.classList.remove('visible');return}
e.style.display='none';t.style.display='flex';f.classList.add('visible');document.getElementById('footer-count').textContent=items.length;document.getElementById('footer-total').textContent=fmt(items.reduce(function(s,i){return s+toNum(i.product.price)},0));
var h='';items.forEach(function(it,i){var p=resolvePrice(it),st=getStockLabel(it),img=it.product.image||(it.product.images||[])[0]||'',added=it.added?new Date(it.added):null,adtext=added?added.toLocaleDateString('en-AU',{day:'numeric',month:'short'}):'';h+='<div class="card"><a href="product.html?id='+esc(it.product.id||'')+'" class="card_img">'+(img?'<img src="'+esc(img)+'" onerror="this.remove()" alt="">':'')+(p.hasDiscount?'<span class="discount_badge">-'+p.discountPct+'</span>':'')+'</a><a href="product.html?id='+esc(it.product.id||'')+'" class="card_info"><div class="card_title">'+esc(it.product.title||'Untitled')+'</div>'+(it.variants?'<div class="card_variant">'+esc(it.variants)+' · <span class="card_variant_edit" onclick="event.preventDefault();editVariants(\''+esc(it.id)+'\')">Edit</span></div>':'')+'<div class="card_pricing">'+(hasDiscount?'<span class="card_original">'+fmt(p.comparePrice)+'</span>':'')+'<span class="card_price">'+fmt(p.price)+'</span></div><div class="card_meta"><span class="card_stock '+st.cls+'">'+st.label+'</span>'+(adtext?'<span class="card_added">Added '+adtext+'</span>':'')+'</div></a><div class="card_actions"><button class="card_remove" onclick="removeItem(\''+esc(it.id)+'\')" title="Remove">✕</button><button class="card_cart" onclick="addToCart(\''+esc(it.id)+'\')">Add to cart</button></div></div>'});c.innerHTML=h}